$('.btn-add').click(function(){
    window.open("addnew.html","_self")
})
$('.btn-cart').click(function(){
    window.open("cart.html","_self")
})
$('.card-img-top').click(function(){
    window.open("singleview.html","_self")
})
